// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAckx_cSx7ERjGwTBRdQIWt7RStjEuilpQ',
    appId: '1:584108326866:android:1b69a383c55626531c920b',
    messagingSenderId: '584108326866',
    projectId: 'gbtour1-79f08',
    databaseURL: 'https://gbtour1-79f08-default-rtdb.firebaseio.com',
    storageBucket: 'gbtour1-79f08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyP4yx2akSfaEmz9PWgAq6DwB5-AvpwZ0',
    appId: '1:584108326866:ios:fcd2a5772dbb7c641c920b',
    messagingSenderId: '584108326866',
    projectId: 'gbtour1-79f08',
    databaseURL: 'https://gbtour1-79f08-default-rtdb.firebaseio.com',
    storageBucket: 'gbtour1-79f08.appspot.com',
    iosClientId: '584108326866-0i1j7k6t3p5fcfr3h0gsi211vpvs05vr.apps.googleusercontent.com',
    iosBundleId: 'com.example.gbTour',
  );
}
